/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.transat.client.applet;

/**
 *
 * @author gaetan
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_createAccount = new javax.swing.JButton();
        b_login = new javax.swing.JButton();
        b_play = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        b_createAccount.setText("Créer un compte");
        b_createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_createAccountActionPerformed(evt);
            }
        });

        b_login.setText("Se connecter");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        b_play.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        b_play.setText("JOUER");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(b_createAccount)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b_login)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(b_play, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(285, 285, 285))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(b_createAccount)
                    .add(b_login))
                .add(104, 104, 104)
                .add(b_play, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(355, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_createAccountActionPerformed
        System.out.println("CREATE ACCOUNT");
        Transat t = (Transat) this.getParent().getParent().getParent();
        t.changeMode(Transat.MODE_SIGNUP);
    }//GEN-LAST:event_b_createAccountActionPerformed

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        System.out.println("LOGIN");
        Transat t = (Transat) this.getParent().getParent().getParent();
        t.changeMode(Transat.MODE_LOGIN);
    }//GEN-LAST:event_b_loginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_createAccount;
    private javax.swing.JButton b_login;
    private javax.swing.JButton b_play;
    // End of variables declaration//GEN-END:variables
}
