/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.transat.client.applet;

import com.transat.client.utils.HttpResponse;
import com.transat.client.utils.HttpUtils;
import com.transat.client.utils.Log;
import java.io.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author gaetan
 */
public class SignupPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignupPanel
     */
    public SignupPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_title = new javax.swing.JLabel();
        l_email = new javax.swing.JLabel();
        l_mdp = new javax.swing.JLabel();
        l_pseudo = new javax.swing.JLabel();
        t_pseudo = new javax.swing.JTextField();
        t_email = new javax.swing.JTextField();
        t_mdp = new javax.swing.JTextField();
        b_ok = new javax.swing.JButton();
        b_back = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        l_title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        l_title.setText("Créer un compte");

        l_email.setText("E-mail : ");

        l_mdp.setText("Mot de passe : ");

        l_pseudo.setText("Pseudo : ");

        t_pseudo.setPreferredSize(new java.awt.Dimension(100, 28));

        t_email.setPreferredSize(new java.awt.Dimension(100, 28));

        t_mdp.setPreferredSize(new java.awt.Dimension(100, 28));

        b_ok.setText("Envoyer !");
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        b_back.setText("<--");
        b_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(l_mdp)
                            .add(l_email)
                            .add(l_pseudo))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(b_ok)
                            .add(t_pseudo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(t_email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(t_mdp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(b_back)
                        .add(253, 253, 253)
                        .add(l_title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                .add(376, 376, 376))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(l_title)
                        .add(66, 66, 66)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(l_pseudo)
                            .add(t_pseudo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(l_email)
                            .add(t_email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(l_mdp)
                            .add(t_mdp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(35, 35, 35)
                        .add(b_ok))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(b_back, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        l_title.getAccessibleContext().setAccessibleName("label_title");
        l_email.getAccessibleContext().setAccessibleName("l_email");
        l_mdp.getAccessibleContext().setAccessibleName("l_mdp");
        l_pseudo.getAccessibleContext().setAccessibleName("l_pseudo");
        t_pseudo.getAccessibleContext().setAccessibleName("t_pseudo");
        t_email.getAccessibleContext().setAccessibleName("t_email");
        t_mdp.getAccessibleContext().setAccessibleName("t_mdp");
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //--------------------------------------
    //  CLICK
    //--------------------------------------
    // ok button
    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        Log.v("signup request");
        
        String pseudo = t_pseudo.getText();
        String email = t_email.getText();
        String password = t_mdp.getText();
        
        // CLIC BOUTON LOGIN
        if( pseudo.length()>0 && password.length()>0 )
        {
            String url = "http://localhost:9000/user/read?pseudo="+pseudo+"&password="+password;
            HttpResponse response = HttpUtils.getInstance().sendRequestGet( url );
            
            String jsonString = response.text;
            if( jsonString.length() > 0 )
            {
                Log.v(jsonString);
                try {
                        JSONObject obj = new JSONObject( jsonString );
                        Log.v( "response : "+obj.getString("pseudo") );
                        Log.v( "response : "+obj.getString("password") );
                        Log.v( "response : "+obj.getString("email") );
                } catch (JSONException e) {
                        e.printStackTrace();
                }
            }
            else
            {
                    Log.v("Le serveur n'a rien renvoyé :)");
            }
        }
        else
        {

        }
    }//GEN-LAST:event_b_okActionPerformed
    
    
    
    // back button
    private void b_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backActionPerformed
        Transat.instance.changeMode(Transat.MODE_HOME);
    }//GEN-LAST:event_b_backActionPerformed
    
    
    

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_ok;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_mdp;
    private javax.swing.JLabel l_pseudo;
    private javax.swing.JLabel l_title;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_mdp;
    private javax.swing.JTextField t_pseudo;
    // End of variables declaration//GEN-END:variables
}
