/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.transat.client.applet;

import com.transat.client.applet.HomePanel;
import com.transat.client.applet.LoginPanel;
import com.transat.client.applet.SignupPanel;
import java.awt.Container;
import java.awt.Dimension;

/**
 *
 * @author gaetan
 */
public class Transat extends javax.swing.JApplet {

    
    //------------------------------------------
    //  STATIC
    //------------------------------------------
    public static Transat instance = null;
    public static final int MODE_NONE = 0;
    public static final int MODE_HOME = 1;
    public static final int MODE_SIGNUP = 2;
    public static final int MODE_LOGIN = 3;
    
    
    
    //------------------------------------------
    //  ATTRIBUTES
    //------------------------------------------
    private HomePanel homePanel = new HomePanel();
    private LoginPanel loginPanel = new LoginPanel();
    private SignupPanel signupPanel = new SignupPanel();
    
    private int MODE = MODE_NONE;
    
    
    
    
    /**
     * Initializes the applet Transat
     */
    @Override
    public void init() {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the applet
         */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        // store reference to change mode later
        Transat.instance = this;

        this.setContentPane( new HomePanel() );
    }
    
    
    
    
    
    //------------------------------------
    //  METHODS
    //------------------------------------
    public void changeMode( int newMode )
    {
        switch( newMode )
        {
            case Transat.MODE_NONE:
                this.MODE = MODE_NONE;
                this.repaint();
                break;
            case Transat.MODE_SIGNUP:
                this.MODE = MODE_SIGNUP;
                this.setContentPane( new SignupPanel() );
                this.repaint();
                break;
            case Transat.MODE_LOGIN:
                this.MODE = MODE_LOGIN;
                this.setContentPane( new LoginPanel() );
                this.repaint();
                break;
            case Transat.MODE_HOME:
                this.MODE = MODE_HOME;
                this.setContentPane( new HomePanel() );
                this.repaint();
                break;
        }
        
        
        
        
    }
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
